# coding: utf-8

"""
    Open Enterprise Agent API Reference

     The Open Enterprise Agent API facilitates the integration and management of self-sovereign identity capabilities within applications. It supports DID (Decentralized Identifiers) management, verifiable credential exchange, and secure messaging based on DIDComm standards. The API is designed to be interoperable with various blockchain and DLT (Distributed Ledger Technology) platforms, ensuring wide compatibility and flexibility. Key features include connection management, credential issuance and verification, and secure, privacy-preserving communication between entities. Additional information and the full list of capabilities can be found in the [Open Enterprise Agent documentation](https://docs.atalaprism.io/docs/category/prism-cloud-agent)   # noqa: E501

    OpenAPI spec version: 1.31.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateEntityRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'wallet_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'wallet_id': 'walletId'
    }

    def __init__(self, id=None, name=None, wallet_id=None):  # noqa: E501
        """CreateEntityRequest - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._wallet_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        if wallet_id is not None:
            self.wallet_id = wallet_id

    @property
    def id(self):
        """Gets the id of this CreateEntityRequest.  # noqa: E501

        The new `id` of the entity to be created. If this field is not provided, the server will generate a new UUID for the entity  # noqa: E501

        :return: The id of this CreateEntityRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CreateEntityRequest.

        The new `id` of the entity to be created. If this field is not provided, the server will generate a new UUID for the entity  # noqa: E501

        :param id: The id of this CreateEntityRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CreateEntityRequest.  # noqa: E501

        The new `name` of the entity to be created. If this field is not provided, the server will generate a random name for the entity  # noqa: E501

        :return: The name of this CreateEntityRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateEntityRequest.

        The new `name` of the entity to be created. If this field is not provided, the server will generate a random name for the entity  # noqa: E501

        :param name: The name of this CreateEntityRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def wallet_id(self):
        """Gets the wallet_id of this CreateEntityRequest.  # noqa: E501

        The new `walletId` of the entity to be created. If this field is not provided, the server will set the default `walletId`  # noqa: E501

        :return: The wallet_id of this CreateEntityRequest.  # noqa: E501
        :rtype: str
        """
        return self._wallet_id

    @wallet_id.setter
    def wallet_id(self, wallet_id):
        """Sets the wallet_id of this CreateEntityRequest.

        The new `walletId` of the entity to be created. If this field is not provided, the server will set the default `walletId`  # noqa: E501

        :param wallet_id: The wallet_id of this CreateEntityRequest.  # noqa: E501
        :type: str
        """

        self._wallet_id = wallet_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateEntityRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateEntityRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
