# coding: utf-8

"""
    Open Enterprise Agent API Reference

     The Open Enterprise Agent API facilitates the integration and management of self-sovereign identity capabilities within applications. It supports DID (Decentralized Identifiers) management, verifiable credential exchange, and secure messaging based on DIDComm standards. The API is designed to be interoperable with various blockchain and DLT (Distributed Ledger Technology) platforms, ensuring wide compatibility and flexibility. Key features include connection management, credential issuance and verification, and secure, privacy-preserving communication between entities. Additional information and the full list of capabilities can be found in the [Open Enterprise Agent documentation](https://docs.atalaprism.io/docs/category/prism-cloud-agent)   # noqa: E501

    OpenAPI spec version: 1.31.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateManagedDidRequestDocumentTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'public_keys': 'list[ManagedDIDKeyTemplate]',
        'services': 'list[Service]',
        'contexts': 'list[str]'
    }

    attribute_map = {
        'public_keys': 'publicKeys',
        'services': 'services',
        'contexts': 'contexts'
    }

    def __init__(self, public_keys=None, services=None, contexts=None):  # noqa: E501
        """CreateManagedDidRequestDocumentTemplate - a model defined in Swagger"""  # noqa: E501
        self._public_keys = None
        self._services = None
        self._contexts = None
        self.discriminator = None
        if public_keys is not None:
            self.public_keys = public_keys
        if services is not None:
            self.services = services
        if contexts is not None:
            self.contexts = contexts

    @property
    def public_keys(self):
        """Gets the public_keys of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501


        :return: The public_keys of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501
        :rtype: list[ManagedDIDKeyTemplate]
        """
        return self._public_keys

    @public_keys.setter
    def public_keys(self, public_keys):
        """Sets the public_keys of this CreateManagedDidRequestDocumentTemplate.


        :param public_keys: The public_keys of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501
        :type: list[ManagedDIDKeyTemplate]
        """

        self._public_keys = public_keys

    @property
    def services(self):
        """Gets the services of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501


        :return: The services of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501
        :rtype: list[Service]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this CreateManagedDidRequestDocumentTemplate.


        :param services: The services of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501
        :type: list[Service]
        """

        self._services = services

    @property
    def contexts(self):
        """Gets the contexts of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501


        :return: The contexts of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501
        :rtype: list[str]
        """
        return self._contexts

    @contexts.setter
    def contexts(self, contexts):
        """Sets the contexts of this CreateManagedDidRequestDocumentTemplate.


        :param contexts: The contexts of this CreateManagedDidRequestDocumentTemplate.  # noqa: E501
        :type: list[str]
        """

        self._contexts = contexts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateManagedDidRequestDocumentTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateManagedDidRequestDocumentTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
