# coding: utf-8

"""
    Open Enterprise Agent API Reference

     The Open Enterprise Agent API facilitates the integration and management of self-sovereign identity capabilities within applications. It supports DID (Decentralized Identifiers) management, verifiable credential exchange, and secure messaging based on DIDComm standards. The API is designed to be interoperable with various blockchain and DLT (Distributed Ledger Technology) platforms, ensuring wide compatibility and flexibility. Key features include connection management, credential issuance and verification, and secure, privacy-preserving communication between entities. Additional information and the full list of capabilities can be found in the [Open Enterprise Agent documentation](https://docs.atalaprism.io/docs/category/prism-cloud-agent)   # noqa: E501

    OpenAPI spec version: 1.31.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ManagedDID(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'did': 'str',
        'long_form_did': 'str',
        'status': 'str'
    }

    attribute_map = {
        'did': 'did',
        'long_form_did': 'longFormDid',
        'status': 'status'
    }

    def __init__(self, did=None, long_form_did=None, status=None):  # noqa: E501
        """ManagedDID - a model defined in Swagger"""  # noqa: E501
        self._did = None
        self._long_form_did = None
        self._status = None
        self.discriminator = None
        self.did = did
        if long_form_did is not None:
            self.long_form_did = long_form_did
        self.status = status

    @property
    def did(self):
        """Gets the did of this ManagedDID.  # noqa: E501

        A managed DID  # noqa: E501

        :return: The did of this ManagedDID.  # noqa: E501
        :rtype: str
        """
        return self._did

    @did.setter
    def did(self, did):
        """Sets the did of this ManagedDID.

        A managed DID  # noqa: E501

        :param did: The did of this ManagedDID.  # noqa: E501
        :type: str
        """
        if did is None:
            raise ValueError("Invalid value for `did`, must not be `None`")  # noqa: E501

        self._did = did

    @property
    def long_form_did(self):
        """Gets the long_form_did of this ManagedDID.  # noqa: E501

        A long-form DID. Mandatory when status is not `PUBLISHED` and optional when status is `PUBLISHED`  # noqa: E501

        :return: The long_form_did of this ManagedDID.  # noqa: E501
        :rtype: str
        """
        return self._long_form_did

    @long_form_did.setter
    def long_form_did(self, long_form_did):
        """Sets the long_form_did of this ManagedDID.

        A long-form DID. Mandatory when status is not `PUBLISHED` and optional when status is `PUBLISHED`  # noqa: E501

        :param long_form_did: The long_form_did of this ManagedDID.  # noqa: E501
        :type: str
        """

        self._long_form_did = long_form_did

    @property
    def status(self):
        """Gets the status of this ManagedDID.  # noqa: E501

        A status indicating a publication state of a DID in the wallet (e.g. `PUBLICATION_PENDING`, `PUBLISHED`). Does not represent DID a lifecyle (e.g. `deactivated`, `recovered`, `updated`).  # noqa: E501

        :return: The status of this ManagedDID.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ManagedDID.

        A status indicating a publication state of a DID in the wallet (e.g. `PUBLICATION_PENDING`, `PUBLISHED`). Does not represent DID a lifecyle (e.g. `deactivated`, `recovered`, `updated`).  # noqa: E501

        :param status: The status of this ManagedDID.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ManagedDID, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ManagedDID):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
