# coding: utf-8

"""
    Open Enterprise Agent API Reference

     The Open Enterprise Agent API facilitates the integration and management of self-sovereign identity capabilities within applications. It supports DID (Decentralized Identifiers) management, verifiable credential exchange, and secure messaging based on DIDComm standards. The API is designed to be interoperable with various blockchain and DLT (Distributed Ledger Technology) platforms, ensuring wide compatibility and flexibility. Key features include connection management, credential issuance and verification, and secure, privacy-preserving communication between entities. Additional information and the full list of capabilities can be found in the [Open Enterprise Agent documentation](https://docs.atalaprism.io/docs/category/prism-cloud-agent)   # noqa: E501

    OpenAPI spec version: 1.31.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.issue_credentials_protocol_api import IssueCredentialsProtocolApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIssueCredentialsProtocolApi(unittest.TestCase):
    """IssueCredentialsProtocolApi unit test stubs"""

    def setUp(self):
        self.api = IssueCredentialsProtocolApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_credential_offer(self):
        """Test case for accept_credential_offer

        As a holder, accept a new credential offer received from another issuer Agent.  # noqa: E501
        """
        pass

    def test_create_credential_offer(self):
        """Test case for create_credential_offer

        As a credential issuer, create a new credential offer that will be sent to a holder Agent.  # noqa: E501
        """
        pass

    def test_get_credential_record(self):
        """Test case for get_credential_record

        Retrieves a specific issue credential flow record from the Agent's database based on its unique `recordId`.  # noqa: E501
        """
        pass

    def test_get_credential_records(self):
        """Test case for get_credential_records

        Retrieves the list of issue credential records from the Agent's database.  # noqa: E501
        """
        pass

    def test_issue_credential(self):
        """Test case for issue_credential

        As an issuer, issues the verifiable credential related the identified issuance flow record.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
