# coding: utf-8

"""
    Open Enterprise Agent API Reference

     The Open Enterprise Agent API facilitates the integration and management of self-sovereign identity capabilities within applications. It supports DID (Decentralized Identifiers) management, verifiable credential exchange, and secure messaging based on DIDComm standards. The API is designed to be interoperable with various blockchain and DLT (Distributed Ledger Technology) platforms, ensuring wide compatibility and flexibility. Key features include connection management, credential issuance and verification, and secure, privacy-preserving communication between entities. Additional information and the full list of capabilities can be found in the [Open Enterprise Agent documentation](https://docs.atalaprism.io/docs/category/prism-cloud-agent)   # noqa: E501

    OpenAPI spec version: 1.31.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.did_registrar_api import DIDRegistrarApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDIDRegistrarApi(unittest.TestCase):
    """DIDRegistrarApi unit test stubs"""

    def setUp(self):
        self.api = DIDRegistrarApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_did_registrar_dids(self):
        """Test case for get_did_registrar_dids

        List all DIDs stored in the agent's wallet  # noqa: E501
        """
        pass

    def test_get_did_registrar_dids_didref(self):
        """Test case for get_did_registrar_dids_didref

        Get a specific DID stored in the agent's wallet  # noqa: E501
        """
        pass

    def test_post_did_registrar_dids(self):
        """Test case for post_did_registrar_dids

        Create an unpublished PRISM DID and store it in the agent's wallet  # noqa: E501
        """
        pass

    def test_post_did_registrar_dids_didref_deactivations(self):
        """Test case for post_did_registrar_dids_didref_deactivations

        Deactivate DID in the agent's wallet and post deactivate operation to the VDR  # noqa: E501
        """
        pass

    def test_post_did_registrar_dids_didref_publications(self):
        """Test case for post_did_registrar_dids_didref_publications

        Publish the DID stored in the agent's wallet to the VDR  # noqa: E501
        """
        pass

    def test_post_did_registrar_dids_didref_updates(self):
        """Test case for post_did_registrar_dids_didref_updates

        Update DID in the agent's wallet and post update operation to the VDR  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
