# coding: utf-8

"""
    Open Enterprise Agent API Reference

     The Open Enterprise Agent API facilitates the integration and management of self-sovereign identity capabilities within applications. It supports DID (Decentralized Identifiers) management, verifiable credential exchange, and secure messaging based on DIDComm standards. The API is designed to be interoperable with various blockchain and DLT (Distributed Ledger Technology) platforms, ensuring wide compatibility and flexibility. Key features include connection management, credential issuance and verification, and secure, privacy-preserving communication between entities. Additional information and the full list of capabilities can be found in the [Open Enterprise Agent documentation](https://docs.atalaprism.io/docs/category/prism-cloud-agent)   # noqa: E501

    OpenAPI spec version: 1.31.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.credential_status_list_api import CredentialStatusListApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCredentialStatusListApi(unittest.TestCase):
    """CredentialStatusListApi unit test stubs"""

    def setUp(self):
        self.api = CredentialStatusListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_credential_status_list_endpoint(self):
        """Test case for get_credential_status_list_endpoint

        Fetch credential status list by its ID  # noqa: E501
        """
        pass

    def test_patch_credential_status_revoke_credential_id(self):
        """Test case for patch_credential_status_revoke_credential_id

        Revoke a credential by its ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
